# Docker Compose file for TurtleBot Behavior Examples
#
# Usage:
#
# To build the images:
#   docker compose build
#
# To start up a specific service by name:
#   docker compose up <service_name>
#
# To open an interactive shell to a running container:
#   docker exec -it <container_name> bash

services:
  # Base image containing dependencies.
  base:
    image: v2x-ros-conversion:base
    build:
      context: ..
      dockerfile: Dockerfile
      target: base_image
  dev:
    image: v2x-ros-conversion:dev
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        - ROS_DISTRO=${ROS_DISTRO:-humble}
      target: dev
    # Interactive shell
    stdin_open: true
    tty: true
    # Networking and IPC for ROS 2
    network_mode: host
    ipc: host
    # Needed to display graphical applications
    privileged: True
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
      - /home/vboxuser/Leidos/v2x-ros-conversion:/home/carma/src/ros-conversion:rw
      - /home/vboxuser/Leidos/carma-msgs:/home/carma/src/CARMAMsgs:rw
      - /home/vboxuser/Leidos/J2735-2024/J2735ASN_202409:/home/carma/src/j2735_202409:ro
      - vscode-server:/home/carma/.vscode-server:rw
      - /home/vboxuser/.claude:/home/carma/.claude:rw
    command: sleep infinity

volumes:
  vscode-server:
